### ISSUE TITLE
Question: Can a TileService be responsible for more than one tile?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/AnimatorDurationTile#10]
Can it also hide the potential ones?

**Comment by nickbutcher** [comment]
No, an app can have multiple `TileService`s but each `TileService` provides a single `Tile`.

**Comment by AndroidDeveloperLB** [comment]
That's too bad. I wonder why they did it this way.
Maybe for preventing too many tiles of apps?
