### ISSUE TITLE
Window animation scale and Transition animation scale

### ISSUE THREAD

**Issue by reline** [nickbutcher/AnimatorDurationTile#11]
Would either of these be reasonable to add to this project? I must still go and manually disable these two scales when doing certain espresso tests, and as they are directly next to the Animator duration scale it defeats the purpose of providing quick access.

**Comment by nickbutcher** [comment]
I'm inclined not to add these settings as this tile is intended for helping you author animations. @JoseAlcerreca do you have any suggestions for better ways to control animations while running espresso tests?

**Comment by JoseAlcerreca** [comment]
They would be handy to help author and review other types of animations. Why is it only changing the scale of one?

On the other hand, adding the functionality would be straightforward @Reline, you can fork this and modify it.

**Comment by reline** [comment]
Awesome, thanks for the feedback!

**Comment by nickbutcher** [comment]
I only control the Animator Duration as that is the only one i've found useful while authoring animations! I'd like to keep this app focused i.e. not offering multiple tiles so will close for now, but as @JoseAlcerreca says, that should be very easy to add so feel free to fork! Good luck.
