### ISSUE TITLE
Why on earth did you use global security settings???

### ISSUE THREAD

**Issue by ghost** [nickbutcher/AnimatorDurationTile#12]
That renders the whole git repository useless... Or at least hard to work with.

And a shame... This is a very nice and useful animation!

**Comment by nickbutcher** [comment]
This is the only way to alter the global animator scale.

**Comment by ghost** [comment]
no way. really? got to be a way to do the same without messing with the global settings.
Anyway... If I can get it done without it, I will post here.

**Comment by fukemy** [comment]
@rubimazaki waiting for your update. I like u more than nickbutcher
