### ISSUE TITLE
没啥没看到控制按钮，执行了权限命令adb shell pm grant uk.co.nickbutcher.animatordurationtile android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by huazhiyuan2008** [nickbutcher/AnimatorDurationTile#2]
![image](https://cloud.githubusercontent.com/assets/2877748/19219499/6d8d14d8-8e47-11e6-8c83-cb884eb4e02b.png)

![image](https://cloud.githubusercontent.com/assets/2877748/19219504/9a45bca0-8e47-11e6-8041-b284a64d5ce0.png)

**Comment by nickbutcher** [comment]
You need to edit your quick settings and add this tile.

http://www.howtogeek.com/231078/use-android-6.0%E2%80%99s-hidden-system-ui-tuner-to-customize-your-quick-settings-and-status-bar/

**Comment by huazhiyuan2008** [comment]
Thanks, System UI Tuner include from Android 6.0。And my emulator is 5.0

**Comment by nickbutcher** [comment]
The `minSdkVersion` of this app is 24 as that is when the Quick Settings `Tile` API was added. You cannot run this on Android 5.0.
