### ISSUE TITLE
Is it possible the tiles don't get removed after uninstall?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/AnimatorDurationTile#3]
I've just noticed it. 
I think it's a bug on the OS...
I've reported about it here:
https://code.google.com/p/android/issues/detail?id=225234

**Comment by nickbutcher** [comment]
Thanks for filing but as you point out, this sounds like an OS bug so closing this issue.

**Comment by AndroidDeveloperLB** [comment]
Can you please check it out though? Maybe fix on Android 7.1 ?
