### ISSUE TITLE
Question: is it possible to also toggle other developer options settings?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/AnimatorDurationTile#4]
Examples:
"Profile GPU rendering" 
"show CPU usage"
"debug GPU overdraw"
"show layout bounds"
"pointer location"
"demo mode"
"take bug report"
?

**Comment by nickbutcher** [comment]
I haven't looked into this but as this issue is not related to this app, i'm closing it.

**Comment by AndroidDeveloperLB** [comment]
ok, was just curious.
