### ISSUE TITLE
Question: which features do the tiles have?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/AnimatorDurationTile#6]
Do we have those features:
1. Single click I know you have, but do you also have long click?I've noticed that long clicking on the tile will actually show the app info screen. Is there a way to change this?
2. , double click?
3. animation between states?
4. ability to put dynamic image (for example for a compass to show the north every second or so)?
5. Ability to add more tiles as the user wishes (and only one service for all) ...

**Comment by nickbutcher** [comment]
I'm going to direct you to the Tile documentation for these questions:

https://developer.android.com/reference/android/service/quicksettings/Tile.html

**Comment by AndroidDeveloperLB** [comment]
I don't see answers to those questions there.
