### ISSUE TITLE
APK is broken package

### ISSUE THREAD

**Issue by pishguy** [nickbutcher/AnimatorDurationTile#7]
could you upload correct APK?

**Comment by nickbutcher** [comment]
It works fine for me?! Can you provide more info on what you are seeing? Thanks!

**Comment by nickbutcher** [comment]
Closing due to lack of info. Please reopen with more details if this is still an issue.

**Comment by pishguy** [comment]
could you see this screen shot?  http://rupload.ir/upload/3jtazyoqlxboz1rissw.jpg

file size is 74KB

**Comment by tajchert** [comment]
Same here - OP3T (6.0.1) and Nexus 7 (6.0.1) both report corrupted apk.
Same happens on https://github.com/Stocard/KeepActivitiesTile
Tried both downloading by device browser and loading APK files from PC, also renaming them.

**Comment by tajchert** [comment]
Oh, I see minSdkVersion is 24, not 23 (in my case of both devices). This should be in Readme, also it is weird that it reports broken package nevertheless.

**Comment by nickbutcher** [comment]
Ah yeah, Nougat+ as this is where the Quick Settings API was introduced. I updated the readme.
