### ISSUE TITLE
Consider using tile long-press for popping duration dialog.

### ISSUE THREAD

**Issue by JakeWharton** [nickbutcher/AnimatorDurationTile#8]
By specifying the action `android.service.quicksettings.action.QS_TILE_PREFERENCES` in an activity `<intent-filter>`, long-pressing on tiles from that app will launch that activity. In this case, that could be an invisible activity that hosts a dialog (or just is itself themed like a dialog) which allows the granular configuring of the duration. This should obviate the need for two separate tiles.

**Comment by nickbutcher** [comment]
Great idea!
