### ISSUE TITLE
Feature: "Don't keep activities" Quick Settings Tile

### ISSUE THREAD

**Issue by f-barth** [nickbutcher/AnimatorDurationTile#9]
Thanks for the great work on this quick settings tile @nickbutcher. Will save a lot of settings navigation for my testing :) I was thinking of creating something similar for the "don't keep activities"-setting. 
Would you be interested in extending your current "app" with such a feature (meaning I'd PR the new feature into this repo) or would you recommend to fork and/or create a new repo targeted solely at the "don't keep activities" setting?

**Comment by nickbutcher** [comment]
Thanks! I'd like to keep this app simple and focused so forking sounds like the right route. Good luck!
